[book]
authors = ["Leonard Sch√ºngel"]
language = "en"
src = "src"
title = "Layouting in egui"

[output.html]
additional-css = ["src/custom.css"]

[preprocessor.egui-preproc]
command = "./egui-preproc/target/debug/egui-preproc.exe"