[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
log = "0.4.27"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.70"
